[versions]
neogradle = "7.1.17"
loom = "1.14.9"
maven-artifact = "3.8.1"

[libraries]
neogradle-userdev = { module = "net.neoforged.gradle:userdev", version.ref = "neogradle" }
neogradle-neoform = { module = "net.neoforged.gradle:neoform", version.ref = "neogradle" }
loom = { module = "net.fabricmc:fabric-loom", version.ref = "loom" }
maven-artifact = { module = "org.apache.maven:maven-artifact", version.ref = "maven-artifact" }

[bundles]
neogradle = ["neogradle-userdev", "neogradle-neoform"]
loom = ["loom"]
maven = ["maven-artifact"]